-- create database db_27_2;

use db_27_2;

create table Student_Master_27 (
std_id int auto_increment primary key,
first_name varchar(75),
last_name varchar(75),
email varchar(70),
number int,
stream varchar(35),
age int,
city varchar(55),
gender varchar(15),
created_date timestamp(6) not null default current_timestamp(6) on update current_timestamp(6)
);

select * from Student_Master_27;

Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Kore','Vacuva','Kore.Vacuva@gmail.com',8925132,'Science',19,'Caracas','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jemie','Corabella','Jemie.Corabella@gmail.com',7194982,'Arts',21,'La Serena','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Kate','Vivle','Kate.Vivle@gmail.com',8613090,'Science',22,'Antananarivo','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Farrah','Francene','Farrah.Francene@gmail.com',8770752,'Commerce',21,'Livingstone','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Sherrie','Klotz','Sherrie.Klotz@gmail.com',8162747,'Commerce',19,'Birkirkara','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Valera','Vorster','Valera.Vorster@gmail.com',7905940,'Science',19,'Wonsan','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Nariko','Halsey','Nariko.Halsey@gmail.com',7992880,'Commerce',19,'Hamburg','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Carol-Jean','Kannry','Carol-Jean.Kannry@gmail.com',7224625,'Arts',21,'Kano','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Frances','Berl','Frances.Berl@gmail.com',8801183,'Commerce',22,'Nouakchott','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jorry','Presber','Jorry.Presber@gmail.com',7302947,'Science',22,'Nukulaelae','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jerry','Dalli','Jerry.Dalli@gmail.com',8554680,'Commerce',19,'Phuket (city)','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Gabi','Robertson','Gabi.Robertson@gmail.com',7518031,'Science',19,'Liverpool','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Adelle','Frendel','Adelle.Frendel@gmail.com',7556181,'Commerce',20,'Wichita','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Augustine','Zeeba','Augustine.Zeeba@gmail.com',8153745,'Science',19,'Tripoli','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Cissiee','Katrine','Cissiee.Katrine@gmail.com',8772036,'Science',19,'Malang','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jennica','Etom','Jennica.Etom@gmail.com',8682735,'Commerce',19,'Kunming','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Hayley','Center','Hayley.Center@gmail.com',8337354,'Science',22,'Chiang Mai','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Adelle','Poppy','Adelle.Poppy@gmail.com',7391857,'Commerce',20,'Kuwait City','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Sam','Cimbura','Sam.Cimbura@gmail.com',8461685,'Arts',21,'Shigatse','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Rivalee','Thornburg','Rivalee.Thornburg@gmail.com',8651674,'Science',19,'Adak','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lucille','Sprage','Lucille.Sprage@gmail.com',7019387,'Commerce',19,'Shigatse','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Dawn','Lamoree','Dawn.Lamoree@gmail.com',8821855,'Science',22,'Arbil','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Chere','Izaak','Chere.Izaak@gmail.com',8823042,'Commerce',22,'Buenos Aires','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Aubrie','Odell','Aubrie.Odell@gmail.com',7374990,'Arts',22,'Thimphu','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Arlina','Paine','Arlina.Paine@gmail.com',8212003,'Commerce',19,'Nouakchott','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jolyn','Brodench','Jolyn.Brodench@gmail.com',7640714,'Commerce',20,'Shanghai','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Hermione','Burch','Hermione.Burch@gmail.com',7510245,'Arts',19,'Huế','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Chere','Bouchard','Chere.Bouchard@gmail.com',8699655,'Science',19,'Phuket (city)','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Bernie','Oneida','Bernie.Oneida@gmail.com',8420145,'Commerce',20,'Nassau','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Angelique','Grobe','Angelique.Grobe@gmail.com',8000612,'Commerce',21,'Tel Aviv','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Arlina','Moina','Arlina.Moina@gmail.com',8471506,'Commerce',19,'Bishkek','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Rivalee','Travax','Rivalee.Travax@gmail.com',8827010,'Commerce',22,'Sydney','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Abbie','Roscoe','Abbie.Roscoe@gmail.com',8926169,'Arts',21,'São Paulo','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Valera','Docilla','Valera.Docilla@gmail.com',7802992,'Arts',22,'Libreville','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Sara-Ann','Rheingold','Sara-Ann.Rheingold@gmail.com',7863048,'Arts',19,'Cleveland','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Konstance','Diogenes','Konstance.Diogenes@gmail.com',7724932,'Science',22,'Sarajevo','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Louella','Mozelle','Louella.Mozelle@gmail.com',7976166,'Commerce',21,'London','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Marguerite','Lewes','Marguerite.Lewes@gmail.com',7702251,'Science',22,'Montreal','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Charmaine','Phyllis','Charmaine.Phyllis@gmail.com',7153680,'Arts',20,'Rome','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Cordi','Gamaliel','Cordi.Gamaliel@gmail.com',8311856,'Science',22,'Kabul','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Tani','Strephon','Tani.Strephon@gmail.com',8478845,'Commerce',20,'Dalian','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lorenza','Fosque','Lorenza.Fosque@gmail.com',7555604,'Commerce',20,'Brisbane','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ronna','Pettiford','Ronna.Pettiford@gmail.com',8485423,'Arts',19,'Tokyo','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Felice','Susannah','Felice.Susannah@gmail.com',8184266,'Arts',19,'Recife','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lexine','Croix','Lexine.Croix@gmail.com',8865059,'Arts',19,'Patna','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Christy','Schonfeld','Christy.Schonfeld@gmail.com',8040736,'Science',21,'Pittsburgh','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Damaris','Fleeta','Damaris.Fleeta@gmail.com',8128978,'Arts',19,'Doha','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Nannie','Alejoa','Nannie.Alejoa@gmail.com',8812009,'Science',21,'Labasa','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ofilia','Celestine','Ofilia.Celestine@gmail.com',8723848,'Commerce',22,'San José','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Dode','Jerold','Dode.Jerold@gmail.com',8014835,'Commerce',20,'Xining','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Nananne','Khorma','Nananne.Khorma@gmail.com',8460391,'Arts',21,'Padang','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Orelia','Rosette','Orelia.Rosette@gmail.com',7912134,'Commerce',20,'Avarua','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Marti','Angelis','Marti.Angelis@gmail.com',8811201,'Science',21,'Puerto Williams','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lorenza','Imelida','Lorenza.Imelida@gmail.com',8232418,'Commerce',20,'Fortaleza','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Frieda','Salchunas','Frieda.Salchunas@gmail.com',7112589,'Arts',20,'Saskatoon','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Mathilda','Fredi','Mathilda.Fredi@gmail.com',8371504,'Arts',21,'São José dos Campos','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Johna','Deny','Johna.Deny@gmail.com',8426827,'Science',20,'Mérida','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Yolane','Dash','Yolane.Dash@gmail.com',8086993,'Arts',22,'Ludhiana','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ulrike','Kosey','Ulrike.Kosey@gmail.com',7695434,'Commerce',19,'Málaga','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Alejandra','Gunn','Alejandra.Gunn@gmail.com',8568617,'Commerce',19,'Edinburgh','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Joy','Sothena','Joy.Sothena@gmail.com',8784707,'Science',20,'Quebec City','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Sophia','Gaulin','Sophia.Gaulin@gmail.com',8162268,'Science',22,'Santiago de Cuba','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'June','Jarib','June.Jarib@gmail.com',8739645,'Arts',20,'Minsk','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ricky','Estella','Ricky.Estella@gmail.com',7779744,'Arts',22,'Podgorica','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ninnetta','Klemperer','Ninnetta.Klemperer@gmail.com',8110815,'Arts',20,'Jacksonville','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Eugine','Timon','Eugine.Timon@gmail.com',7622989,'Commerce',22,'Oslo','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Teriann','Chrystel','Teriann.Chrystel@gmail.com',7888074,'Arts',21,'Conakry','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Amalie','Llovera','Amalie.Llovera@gmail.com',8914077,'Science',20,'Lanzhou','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Janeczka','Dituri','Janeczka.Dituri@gmail.com',8436622,'Science',20,'Weno','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Judy','Mata','Judy.Mata@gmail.com',8120473,'Science',19,'Christchurch','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Rebeca','Alcott','Rebeca.Alcott@gmail.com',8799963,'Science',20,'Bulawayo','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ninnetta','Morehouse','Ninnetta.Morehouse@gmail.com',7272564,'Arts',19,'Sacramento','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Brynna','Haerr','Brynna.Haerr@gmail.com',7649551,'Arts',21,'Astana','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Marjie','Egbert','Marjie.Egbert@gmail.com',8134228,'Science',20,'Doha','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Caryl','Latini','Caryl.Latini@gmail.com',7409432,'Commerce',19,'Belém','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Britte','Idelia','Britte.Idelia@gmail.com',8010170,'Arts',20,'Leeds','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Wilma','Lynn','Wilma.Lynn@gmail.com',7561032,'Arts',22,'Leeds','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Berget','Dunkin','Berget.Dunkin@gmail.com',7141021,'Science',22,'Lahore','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Stevana','Rosalba','Stevana.Rosalba@gmail.com',8605495,'Commerce',20,'Mecca','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Sybille','Primalia','Sybille.Primalia@gmail.com',7642001,'Arts',20,'Managua','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Dagmar','Brunell','Dagmar.Brunell@gmail.com',8393039,'Science',21,'Bursa','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Tami','Jotham','Tami.Jotham@gmail.com',7724888,'Science',22,'Cuiabá','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Sharai','Liebermann','Sharai.Liebermann@gmail.com',7036579,'Science',21,'Huế','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ebonee','Therine','Ebonee.Therine@gmail.com',8396639,'Science',21,'Bujumbura','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Alie','Ahab','Alie.Ahab@gmail.com',7584994,'Arts',19,'Incheon','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Aeriela','Keily','Aeriela.Keily@gmail.com',7103023,'Science',22,'Multan','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Melina','Sperling','Melina.Sperling@gmail.com',7386408,'Arts',19,'Gothenburg','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Sam','Papageno','Sam.Papageno@gmail.com',7940935,'Commerce',22,'Nizhny Novgorod','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jordan','Angelis','Jordan.Angelis@gmail.com',7789922,'Arts',19,'Tartu','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jsandye','Socha','Jsandye.Socha@gmail.com',8576035,'Science',21,'Barcelona','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Gusty','Llovera','Gusty.Llovera@gmail.com',7873154,'Science',22,'Ouagadougou','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Cathyleen','Egbert','Cathyleen.Egbert@gmail.com',8446527,'Arts',21,'Helsinki','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Nanete','Ivens','Nanete.Ivens@gmail.com',8232626,'Science',19,'Boston','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Susette','Estella','Susette.Estella@gmail.com',7330895,'Arts',21,'Baltimore','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Bernardine','Allys','Bernardine.Allys@gmail.com',8362121,'Arts',22,'Odessa','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Harrietta','Briney','Harrietta.Briney@gmail.com',8924294,'Arts',22,'Jakarta','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Dorice','Kenney','Dorice.Kenney@gmail.com',8910604,'Science',20,'Riga','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lucy','Larochelle','Lucy.Larochelle@gmail.com',8732914,'Arts',21,'Khartoum','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Sabina','Mandler','Sabina.Mandler@gmail.com',7822946,'Arts',21,'Incheon','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lorenza','Belldas','Lorenza.Belldas@gmail.com',7793995,'Arts',22,'City of Halifax','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Gabriellia','Sheng','Gabriellia.Sheng@gmail.com',8644074,'Commerce',19,'Valparaíso','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Celestyna','Torray','Celestyna.Torray@gmail.com',8214011,'Science',21,'Dammam','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Fina','Judye','Fina.Judye@gmail.com',8274110,'Commerce',20,'Belize City','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Marline','Zenas','Marline.Zenas@gmail.com',8398529,'Science',19,'Juneau','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Edee','Tamsky','Edee.Tamsky@gmail.com',8099151,'Commerce',22,'Port Elizabeth','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Margarette','O''Rourke','Margarette.O''Rourke@gmail.com',7763760,'Science',19,'Singapore','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jaclyn','Malina','Jaclyn.Malina@gmail.com',8822486,'Science',21,'Lilongwe','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Karina','Darbie','Karina.Darbie@gmail.com',7377497,'Science',21,'Miri','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lucille','Shanley','Lucille.Shanley@gmail.com',7750369,'Science',21,'Dar es Salaam','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Tiffie','Septima','Tiffie.Septima@gmail.com',8402151,'Arts',20,'Macapá','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Bettine','Dorothy','Bettine.Dorothy@gmail.com',7807414,'Science',19,'Campo Grande','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Deedee','Sheng','Deedee.Sheng@gmail.com',8316104,'Science',22,'Iquique','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Benita','Eugenia','Benita.Eugenia@gmail.com',8038038,'Science',22,'Tokyo','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Daryl','Erb','Daryl.Erb@gmail.com',7189570,'Commerce',19,'Novosibirsk','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Andree','Reneta','Andree.Reneta@gmail.com',8101764,'Arts',22,'Kandahar','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Romona','Elephus','Romona.Elephus@gmail.com',7923938,'Commerce',21,'Tórshavn','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Arlina','Genna','Arlina.Genna@gmail.com',8255976,'Arts',20,'Arbil','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Annecorinne','Cristi','Annecorinne.Cristi@gmail.com',7140473,'Science',22,'Adana','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Rayna','Poll','Rayna.Poll@gmail.com',7920574,'Arts',22,'Asunción','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Adriana','Secrest','Adriana.Secrest@gmail.com',8791261,'Arts',20,'Durango','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Rori','Ader','Rori.Ader@gmail.com',8032162,'Arts',21,'Belém','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Collen','Catie','Collen.Catie@gmail.com',7050504,'Arts',19,'Seoul','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Tina','Santoro','Tina.Santoro@gmail.com',8935663,'Science',21,'Mérida','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Doralynne','Judye','Doralynne.Judye@gmail.com',8841256,'Science',20,'Bangui','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Cindelyn','Guildroy','Cindelyn.Guildroy@gmail.com',8627831,'Commerce',22,'Luxor','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Evaleen','Sothena','Evaleen.Sothena@gmail.com',7392825,'Arts',19,'Perth','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Arlena','Wandie','Arlena.Wandie@gmail.com',8277522,'Science',19,'Oslo','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Olivette','Desai','Olivette.Desai@gmail.com',8800481,'Science',20,'Paramaribo','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Larine','Merna','Larine.Merna@gmail.com',8345386,'Science',19,'Thiès','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Dania','Greyson','Dania.Greyson@gmail.com',7108804,'Arts',20,'Shijiazhuang','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Frank','Corilla','Frank.Corilla@gmail.com',7337172,'Commerce',21,'Denver','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lulita','Donoghue','Lulita.Donoghue@gmail.com',8285310,'Science',21,'Vitória','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Rani','Tybald','Rani.Tybald@gmail.com',8082562,'Science',20,'Chongjin','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Clo','Roarke','Clo.Roarke@gmail.com',8907140,'Arts',20,'Bulawayo','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ariela','Gaynor','Ariela.Gaynor@gmail.com',7010813,'Science',21,'Malmö','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Amii','Gombach','Amii.Gombach@gmail.com',7570712,'Arts',21,'Makassar','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Willetta','Ferrell','Willetta.Ferrell@gmail.com',7865214,'Commerce',21,'Warsaw','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Tobe','Gavrila','Tobe.Gavrila@gmail.com',7733938,'Arts',19,'Denpasar','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lacie','Timon','Lacie.Timon@gmail.com',8781221,'Science',19,'Perm','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Chandra','Olnee','Chandra.Olnee@gmail.com',7086295,'Commerce',19,'Adak','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Larine','Edison','Larine.Edison@gmail.com',7623040,'Science',20,'Bursa','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Hollie','Pyle','Hollie.Pyle@gmail.com',7114855,'Commerce',22,'Tabriz','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Berget','Hachmin','Berget.Hachmin@gmail.com',8097930,'Science',22,'Chihuahua','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Roseline','Jacqui','Roseline.Jacqui@gmail.com',7347073,'Commerce',22,'Santo Domingo','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Rayna','Erminia','Rayna.Erminia@gmail.com',8185775,'Arts',21,'Niamey','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Henriette','Merna','Henriette.Merna@gmail.com',7266798,'Commerce',22,'Townsville','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Fina','Sandye','Fina.Sandye@gmail.com',8360434,'Commerce',21,'Boa Vista','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Henriette','Kussell','Henriette.Kussell@gmail.com',8333184,'Commerce',22,'Kandy','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Bee','Tjon','Bee.Tjon@gmail.com',7383438,'Arts',22,'Kraków','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Yolane','Muriel','Yolane.Muriel@gmail.com',7703265,'Science',20,'Honiara','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lisette','Dorothy','Lisette.Dorothy@gmail.com',8657946,'Science',22,'Málaga','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Cindelyn','Ogren','Cindelyn.Ogren@gmail.com',7537655,'Arts',21,'Bursa','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Jeanna','Whittaker','Jeanna.Whittaker@gmail.com',7324302,'Commerce',22,'Kharkiv','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Agathe','Erb','Agathe.Erb@gmail.com',7065047,'Arts',21,'Qingdao','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Tressa','Ailyn','Tressa.Ailyn@gmail.com',7985059,'Science',20,'Hanover','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Margalo','Stephie','Margalo.Stephie@gmail.com',7674597,'Commerce',19,'Beirut','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Kellen','Velick','Kellen.Velick@gmail.com',7380610,'Commerce',21,'Barcelona','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Felice','Craggie','Felice.Craggie@gmail.com',7653628,'Arts',19,'Sacramento','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Carilyn','Hieronymus','Carilyn.Hieronymus@gmail.com',7859065,'Science',19,'Hangzhou','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Dorthy','Anastatius','Dorthy.Anastatius@gmail.com',8346916,'Arts',20,'N''Djamena','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Phedra','Astra','Phedra.Astra@gmail.com',8982043,'Arts',21,'Koror','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Yolane','Lail','Yolane.Lail@gmail.com',8226944,'Arts',19,'Murmansk','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Hannis','Narton','Hannis.Narton@gmail.com',8999903,'Science',19,'Dublin','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Augustine','Rudolph','Augustine.Rudolph@gmail.com',7067072,'Arts',21,'Iquique','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Natka','Mauer','Natka.Mauer@gmail.com',8216810,'Science',20,'Kabul','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Deirdre','Gilmour','Deirdre.Gilmour@gmail.com',7908182,'Arts',22,'Serekunda','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Elbertina','Georgy','Elbertina.Georgy@gmail.com',8007797,'Science',22,'Algiers','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Minda','Gino','Minda.Gino@gmail.com',8755633,'Science',19,'Lima','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ethel','Scammon','Ethel.Scammon@gmail.com',8812073,'Science',20,'Macapá','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Raina','Salchunas','Raina.Salchunas@gmail.com',8679744,'Commerce',19,'Xining','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Olivette','Lindemann','Olivette.Lindemann@gmail.com',7128771,'Science',21,'Las Vegas','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Arlina','Yoko','Arlina.Yoko@gmail.com',7776560,'Commerce',21,'Birkirkara','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Glenda','Roxanna','Glenda.Roxanna@gmail.com',8546677,'Arts',21,'Saipan','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Codie','Bord','Codie.Bord@gmail.com',8727010,'Science',19,'Enugu','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Bettine','Lea','Bettine.Lea@gmail.com',8678167,'Science',21,'Caracas','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Morganica','Stover','Morganica.Stover@gmail.com',7797342,'Commerce',20,'Tabriz','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Romona','Sawtelle','Romona.Sawtelle@gmail.com',8108119,'Arts',19,'Vatican City','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Elfreda','Kathie','Elfreda.Kathie@gmail.com',7778514,'Arts',22,'Panama City','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Amii','Reneta','Amii.Reneta@gmail.com',8717234,'Arts',19,'Yakutsk','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Elka','Grosz','Elka.Grosz@gmail.com',7973244,'Arts',21,'Omsk','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Audrie','Carbo','Audrie.Carbo@gmail.com',8460999,'Commerce',21,'Belém','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Averyl','Bryna','Averyl.Bryna@gmail.com',8080797,'Commerce',22,'Cebu City','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Lanna','Rodmann','Lanna.Rodmann@gmail.com',7575260,'Arts',19,'New Orleans','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Heida','Grobe','Heida.Grobe@gmail.com',7667542,'Arts',19,'Weno','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Janey','Rosemary','Janey.Rosemary@gmail.com',8358381,'Science',21,'Belfast','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Charissa','Mott','Charissa.Mott@gmail.com',8654644,'Commerce',20,'New Orleans','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Korrie','Concha','Korrie.Concha@gmail.com',7354849,'Science',22,'Ankara','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Yetty','Adore','Yetty.Adore@gmail.com',7111754,'Arts',22,'Lima','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Vivia','Faust','Vivia.Faust@gmail.com',7484140,'Science',22,'São José dos Campos','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Dorene','Anestassia','Dorene.Anestassia@gmail.com',7495567,'Commerce',22,'Longyearbyen','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Hollie','Arne','Hollie.Arne@gmail.com',8805031,'Commerce',22,'Enugu','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Ottilie','Anton','Ottilie.Anton@gmail.com',7611398,'Commerce',22,'Gaborone','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Candy','Amand','Candy.Amand@gmail.com',8282543,'Arts',21,'Cairo','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Annaliese','Middleton','Annaliese.Middleton@gmail.com',7412250,'Commerce',19,'İzmir','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Leontine','Flita','Leontine.Flita@gmail.com',8362754,'Science',19,'Cairo','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Alex','Roarke','Alex.Roarke@gmail.com',8405557,'Commerce',21,'Cartagena','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Rosaline','Brieta','Rosaline.Brieta@gmail.com',8300423,'Arts',21,'Tianjin','Male' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Zsa Zsa','Bohlin','Zsa Zsa.Bohlin@gmail.com',7092294,'Science',19,'Saskatoon','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Mamie','Nikaniki','Mamie.Nikaniki@gmail.com',7752972,'Arts',19,'Detroit','Female' );
Insert Into Student_Master_27 ( first_name, last_name, email, number, stream, age, city, gender) Values ( 'Evita','Alisia','Evita.Alisia@gmail.com',7787854,'Arts',22,'Johannesburg','Female' );
